### ISSUE TITLE
Estructura de Monorepo

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#11]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/pipeline/issues/10
- [ ] https://github.com/alercebroker/pipeline/issues/9
- [ ] https://github.com/alercebroker/pipeline/issues/3
- [ ] https://github.com/alercebroker/pipeline/issues/15
```

Peligro: posiblemente hay que migrar el proceso de CI a otra herramienta, por limitación del plan libre de Github
