### ISSUE TITLE
Pasar pipeline a producción

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#147]
# Descripción
Hasta ahora en ALeRCE hemos estado funcionando con versiones desincronizadas y divergentes de los entornos de prueba y producción. Con el paso del tiempo, la funcionalidad de producción ha quedado en el pasado sin posibilidad de actualización y las versiones nuevas siguen divergiendo cada vez más. Esto terminará este sprint.

La idea es poder operar con la versión más reciente de la pipeline (que hemos testeado tanto en el entorno staging como en el proyecto paralelo de ELAsTiCC). Pero para esto debemos tomar las precauciones correspondientes.

### No perder lo que ya funciona
Los datos provenientes de ZTF se encuentran en la base de datos PostgreSQL conocida como "Alerts Database". Estos datos contienen información de alertas de ZTF desde el año 2019 hasta la fecha y sigue sumando datos cada noche. 

Migrar estos datos al nuevo esquema supone más dificultades que beneficios, por lo que decidimos mantener la funcionalidad de PSQL tanto para los servicios del lado de usuarios como para lo que involucra la pipeline.

Los datos de ZTF que reciba la pipeline nueva deben ser leídos y escritos tanto en PSQL como en MongoDB y deben ser tratados de la misma forma (al menos internamente en la pipeline).

Habrá duplicidad de datos.

### Scribe
El scribe se encarga de escribir los nuevos datos de la pipeline en MongoDB. La nueva versión debe escribir tanto en PSQL como en MongoDB.

### Lightcurve Step
El paso de lightcurve se encarga de obtener la curva de luz completa a partir de la base de datos + los datos nuevos de las alertas. Como los datos van a estar repartidos en PSQL y MongoDB, el step debe hacer las consultas correspondientes a ambas bases de datos y unificar los resultados.

### Datos que ya están en MongoDB vs los nuevos
La base de datos MongoDB que actualmente tiene información de ZTF y ATLAS está desactualizada al comparar con el esquema que usa actualmente la pipeline. Se requiere actualizar esos datos para la compatibilidad con la nueva versión.

```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/pipeline/issues/162
- [ ] https://github.com/alercebroker/pipeline/issues/163
- [ ] https://github.com/alercebroker/pipeline/issues/171
- [ ] https://github.com/alercebroker/pipeline/issues/172
- [ ] https://github.com/alercebroker/pipeline/issues/191
- [ ] https://github.com/alercebroker/pipeline/issues/206
- [ ] https://github.com/alercebroker/pipeline/issues/207
- [ ] https://github.com/alercebroker/pipeline/issues/208
- [ ] https://github.com/alercebroker/pipeline/issues/209
- [ ] https://github.com/alercebroker/pipeline/issues/218
- [ ] https://github.com/alercebroker/pipeline/issues/219
- [ ] https://github.com/alercebroker/pipeline/issues/220
- [ ] https://github.com/alercebroker/pipeline/issues/221
- [ ] https://github.com/alercebroker/pipeline/issues/222
- [ ] https://github.com/alercebroker/pipeline/issues/223
- [ ] https://github.com/alercebroker/pipeline/issues/224
- [ ] https://github.com/alercebroker/infrastructure_provisioning/issues/207
- [ ] https://github.com/alercebroker/pipeline/issues/225
- [ ] https://github.com/alercebroker/pipeline/issues/226
- [ ] https://github.com/alercebroker/pipeline/issues/227
- [ ] https://github.com/alercebroker/pipeline/issues/232
- [ ] https://github.com/alercebroker/pipeline/issues/241
- [ ] https://github.com/alercebroker/pipeline/issues/243
- [ ] https://github.com/alercebroker/pipeline/issues/245
- [ ] https://github.com/alercebroker/pipeline/issues/246
- [ ] https://github.com/alercebroker/pipeline/issues/263
- [ ] https://github.com/alercebroker/pipeline/issues/270
- [ ] https://github.com/alercebroker/pipeline/issues/276
- [ ] https://github.com/alercebroker/pipeline/issues/280
- [ ] https://github.com/alercebroker/pipeline/issues/288
- [ ] https://github.com/alercebroker/pipeline/issues/296
- [ ] https://github.com/alercebroker/pipeline/issues/302
- [ ] https://github.com/alercebroker/pipeline/issues/299
- [ ] https://github.com/alercebroker/pipeline/issues/311
- [ ] https://github.com/alercebroker/pipeline/issues/312
- [ ] https://github.com/alercebroker/pipeline/issues/313
- [ ] https://github.com/alercebroker/pipeline/issues/315
- [ ] https://github.com/alercebroker/pipeline/issues/316
- [ ] https://github.com/alercebroker/web-services/issues/242
- [ ] https://github.com/alercebroker/pipeline/issues/319
- [ ] https://github.com/alercebroker/pipeline/issues/321
```
