### ISSUE TITLE
Crear pipeline de build release candidate

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#157]
Los pasos que debe cumplir la pipeline son:

```[tasklist]
### Tasks
- [ ] Update package version
- [ ] Sync chart appVersion with package version
- [ ] Update chart version
- [ ] Git push
- [ ] Build image
- [ ] Push image to GHCR
```
