### ISSUE TITLE
Crear pipeline de build latest (prod)

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#158]
Esta pipeline se ejecuta con cada release y debe recibir un tag para actualizar las versiones

```[tasklist]
### Tasks
- [x] Update package version (from tag)
- [x] Sync chart appVersion with package version
- [x] Git push
- [x] Build docker image with tag latest and the tag from release
- [x] Push docker image to GHCR
```
