### ISSUE TITLE
Agregar scribe

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#17]
```[tasklist]
### Tasks
- [x] Workflow de test
- [x] Worfklow de build staging
- [x] Worflkow de build production
- [x] Código fuente en directorio scribe/
```

**Comment by ASHuenchuleo** [comment]
Al agregar el build test, me da un error en el workflow por que no encuentra la carpeta scribe. Revisé y no se si entiendo bien pero para hacer el build se saca de main y no de la rama en la que se está trabajando, haciendo que build test no haga nada:
https://github.com/alercebroker/pipeline/blob/29f59abd9d3ceed91c2d9d99803f2e55e2104db2/.github/workflows/build-template.yaml#L42-L46

**Comment by dirodriguezm** [comment]
Lo muevo a DONE
