### ISSUE TITLE
Agregar deployment para alert-archive-step

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#209]
```[tasklist]
### Tasks
- [x] Agregar deployment en CI/CD pipeline staging
- [x] Agregar deployment en CI/CD pipeline production
- [x] Agregar bucket S3 staging con política de retención de datos de 1 día
```
