### ISSUE TITLE
Usar schemaless producer y consumer en todos los steps

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#218]
### Description
To see the messages in AKHQ the producers need to be schemaless. If we use schemaless producer we need to provide the consumer with a schema.

Each step should be updated to use a schemaless producer and provide a schema to the consumer.

Also, the schemas need to be provisioned to akhq web service in the https://github.com/alercebroker/infrastructure_provisioning repo.

```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/pipeline/issues/250
- [ ] https://github.com/alercebroker/pipeline/issues/251
- [ ] https://github.com/alercebroker/pipeline/issues/252
- [ ] https://github.com/alercebroker/pipeline/issues/254
- [ ] https://github.com/alercebroker/pipeline/issues/255
```

### Acceptance criteria
- Messages are visible on akhq.staging.alerce.online

**Comment by dirodriguezm** [comment]
Arreglado varios tests. Falta por corregir: 

- Scribe
- Lightcurve
- Magstats
- LC Classification

**Comment by dirodriguezm** [comment]
## Uso de yaml file para configuración
Optamos por usar yaml directo en el chart como reemplazo de un archivo de settings que lee muchas variables de entorno.

Uno de los problemas de hacerlo de esta forma es cuando las métricas definen una lambda como parámetro en las settings.
La solución que tomé fue hacerlo "a la mala" en el run_step de la siguiente forma:

```python
def update_extra_metrics(settings):
    extra_metrics = settings["METRICS_CONFIG"]["EXTRA_METRICS"]
    extra_metrics = list(
        map(
            lambda x: {**x, "format": "some format"} if x["key"] == "candid" else x,
            extra_metrics,
        )
    )
    settings["METRICS_CONFIG"]["EXTRA_METRICS"] = extra_metrics
    return settings
```
Fuera de este problema es mucho más práctico configurar los steps directo en los charts en lugar del flujo "tradicional":

1. Agregar lectura de variable de entorno en `settings.py`
2. Agregar variable en configmap/secret del chart
3. Agregar variable de entorno en deployment del chart
4. Agregar variable en values del chart
