### ISSUE TITLE
Fix Elasticc

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#286]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/pipeline/issues/287
- [ ] #284
- [ ] https://github.com/alercebroker/pipeline/issues/290
- [ ] https://github.com/alercebroker/pipeline/issues/292
- [ ] https://github.com/alercebroker/pipeline/issues/294
- [ ] https://github.com/alercebroker/pipeline/issues/295
- [ ] https://github.com/alercebroker/pipeline/issues/299
- [ ] https://github.com/alercebroker/pipeline/issues/300
- [ ] https://github.com/alercebroker/pipeline/issues/306
- [ ] https://github.com/alercebroker/pipeline/issues/308
```
