### ISSUE TITLE
Paso a producción de pipeline completa

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#288]
```[tasklist]
### Tasks
- [ ] #218
- [x] Actualizar values que usan schema en entorno prod
- [x] Borrar tabla forced_photometry de PSQL alerts prod
- [x] Recrear tabla forced_photometry en PSQL usando dbplugins comando `dbp initdb`
- [x] Actualizar secrets con la nueva base de datos mongo conectando a la instancia mongos
- [x] Crear release mediante trigger manual de GH Actions para deployment de prod en repo pipeline
- [x] Bajar pipeline anterior, por ejemplo, usando `helm uninstall` a cada release o bien desde el repo infrastructure_provisioning con terraform
```
