### ISSUE TITLE
Agrupar alertas por oid en lugar de aid

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#344]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/pipeline/issues/345
- [ ] https://github.com/alercebroker/pipeline/issues/346
- [ ] https://github.com/alercebroker/pipeline/issues/347
- [ ] https://github.com/alercebroker/pipeline/issues/348
- [ ] https://github.com/alercebroker/pipeline/issues/349
- [ ] https://github.com/alercebroker/pipeline/issues/350
- [ ] https://github.com/alercebroker/pipeline/issues/353
- [ ] https://github.com/alercebroker/pipeline/issues/356
- [ ] https://github.com/alercebroker/pipeline/issues/357
- [ ] https://github.com/alercebroker/pipeline/issues/354
- [ ] https://github.com/alercebroker/pipeline/issues/355
- [ ] https://github.com/alercebroker/pipeline/issues/362
- [ ] https://github.com/alercebroker/pipeline/issues/363
- [ ] https://github.com/alercebroker/pipeline/issues/364
- [ ] https://github.com/alercebroker/pipeline/issues/365
```
