### ISSUE TITLE
Telemetría pipeline

### ISSUE THREAD

**Issue by AlxEnashi** [alercebroker/pipeline#59]
Leer logs dede los PODS de la pipeline

Requerimientos generales
- Extensible a los servicios web (aprobechar el trabajo y usar en ese contexto)
- Que no genere conflictos con prometheus ni pyroscope.
- Los logs a consumir son los warning y errores.
- Con un archivo de configuacion poder definir de cuales pods se consumen los logs y de cuales no en el cluster.

```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/pipeline/issues/82
- [ ] https://github.com/alercebroker/pipeline/issues/83
``` 

### Logs Faltante
La idea progresivamente ir mejorando los logs de los steps

- [ ] Missing keys parsing alerts en sorting hat

**Comment by dirodriguezm** [comment]
Tanto la config. de Fluentbit como el dashboard de grafana ya se encuentran en el repo https://github.com/alercebroker/infrastructure_provisioning para staging.

**Comment by dirodriguezm** [comment]
Está todo listo excepto un paso faltante para cuando las métricas comiencen a llegar con el campo `survey`. Ahí se puede agregar una query a los paneles para filtrar por survey. Esto es `survey.keyword:$survey`
