### ISSUE TITLE
Mantenimiento / mejoras ELaSTiCC

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#60]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/pipeline/issues/61
- [ ] https://github.com/alercebroker/pipeline/issues/105
- [ ] https://github.com/alercebroker/pipeline/issues/64
- [ ] https://github.com/alercebroker/pipeline/issues/84
- [ ] https://github.com/alercebroker/pipeline/issues/107
- [ ] https://github.com/alercebroker/pipeline/issues/63
- [ ] https://github.com/alercebroker/pipeline/issues/62
- [ ] https://github.com/alercebroker/pipeline/issues/132
```
