### ISSUE TITLE
Refactorizar LC classification step para consumir tanto de correction como de features

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#61]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/pipeline/issues/89
- [ ] https://github.com/alercebroker/pipeline/issues/88
- [ ] https://github.com/alercebroker/pipeline/issues/87
- [ ] https://github.com/alercebroker/pipeline/issues/91
- [ ] https://github.com/alercebroker/pipeline/issues/94
```

![Image](https://github.com/alercebroker/pipeline/assets/18015991/0191f670-0aff-4f78-9ef1-0292fcce3e90)

**Comment by AlxEnashi** [comment]
Tarea 1 y Tarea 2 deben hacerse en la misma rama para poder pasar los tests.
La tarea de quitar el parse outputDTO puede hacerse independientemente.
Se necesita agregar un if para correr el ztf classifier como esta ahora.
