### ISSUE TITLE
Deployment Barney

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#63]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/pipeline/issues/6
- [ ] https://github.com/alercebroker/pipeline/issues/121
- [ ] https://github.com/alercebroker/pipeline/issues/122
- [ ] https://github.com/alercebroker/pipeline/issues/123
- [ ] https://github.com/alercebroker/pipeline/issues/135
```
