### ISSUE TITLE
Agregar DB Plugins

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#7]
```[tasklist]
### Tasks
- [x] Agregar DB Plugins como subdirectorio de lib/ usando subtree
- [x] https://github.com/alercebroker/pipeline/issues/86
- [ ] https://github.com/alercebroker/pipeline/issues/99
```
