### ISSUE TITLE
Migración Pants

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#73]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/pipeline/issues/75
- [ ] https://github.com/alercebroker/pipeline/issues/74
- [ ] https://github.com/alercebroker/pipeline/issues/76
```
