### ISSUE TITLE
Continuous Delivery Monorepo

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#77]
# Descripción
Actualmente el proceso de CI termina con la creación de imágenes etiquetadas para staging (push a main) y para producción (release). El objetivo de esta tarea es llevarlo al nivel de despliegue automático de las imágenes creadas en CI.

El proceso debería estar fuertemente inspirado en el proceso de CD para web services (https://github.com/alercebroker/web-services/tree/main/ci), pero con ciertas diferencias.

El proceso de deployment automático para steps de la pipeline es más dificil de verificar, ya que funciona en base a eventos y no existe una forma de diferenciar eventos reales de eventos de prueba, por lo que realizar rollback o pruebas inmediatamente después de un deployment no es trivial.

Es por esto que se decide mantener el proceso de dos etapas. Un proceso automático para deployment a staging y un proceso con intervención manual para el despliegue a producción.

### Despliegue a staging
Este proceso debería llevarse a cabo con cada commit (push) de la rama `main`. 
1. Actualizar versión del step
2. Actualizar versión del chart y sincronizar appVersion con la del step
3. Publicar chart en repositorio helm
4. Construir y publicar imagen docker
5. Desplegar chart actualizado

### Despliegue a producción
Este proceso requiere acción manual mediante la creación de un release y asignación de un tag que represente la actualización en curso (ej: incrementar versión major, minor o patch).

Los pasos son equivalentes con el despliegue a staging

1. Actualizar versión del step según tag
2. Actualizar versión del chart y sincronizar appVersion con la del step
3. Publicar chart en repositorio helm
4. Construir y publicar imagen docker
5. Desplegar chart actualizado

```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/pipeline/issues/156
- [ ] https://github.com/alercebroker/pipeline/issues/157
- [ ] https://github.com/alercebroker/pipeline/issues/158
- [ ] https://github.com/alercebroker/pipeline/issues/159
- [ ] https://github.com/alercebroker/pipeline/issues/160
- [ ] https://github.com/alercebroker/pipeline/issues/161
```
