### ISSUE TITLE
Crear pipeline de despliegue

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#80]
```[tasklist]
### Tasks
- [ ] Los charts viven en el monorepo
- [ ] La versión del chart se actualiza automáticamente con push a main (pre-release)
- [ ] La versión del chart se actualiza automáticamente con tag del release (release)
- [ ] La versión de la aplicación en el chart (appVersion) se linkea con la versión del step 
- [ ] Se empaqueta (`helm package`) el chart y se despliega al cluster (`helm upgrade`)
```

**Comment by dirodriguezm** [comment]
Se puede reutilizar el flujo que se hizo en https://github.com/alercebroker/web-services/tree/main/ci


![](https://github.com/alercebroker/web-services/blob/main/ci/diagram.png)

**Comment by dirodriguezm** [comment]
Lo cierro para desglosarlo en otro issue.
