### ISSUE TITLE
Agregar librerías

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#9]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/pipeline/issues/8
- [ ] https://github.com/alercebroker/pipeline/issues/7
- [ ] https://github.com/alercebroker/pipeline/issues/16
- [ ] https://github.com/alercebroker/pipeline/issues/42
- [ ] https://github.com/alercebroker/pipeline/issues/69
- [ ] https://github.com/alercebroker/pipeline/issues/71
- [ ] https://github.com/alercebroker/pipeline/issues/72
- [ ] https://github.com/alercebroker/pipeline/issues/6
```
